### ISSUE TITLE
Keeping track of new data from server / API

### ISSUE THREAD

**Issue by MichaelBieniek** [JustinSchieck/PhoenixRetroBoard#10]
@lawjeremy @JustinSchieck 
How do we want to keep track of _new_ content from API?
* Does the UI poll the back-end for an indicator of new data?
* Does both the UI and back-end keep track of a lastDeltaDate, and if these are different, request and merge the new data?
* Do we use hashes of full content array for this purpose?

**Comment by JustinSchieck** [comment]
@MichaelBieniek @lawjeremy will bring up tomorrow morning for 10 mins. Speak tomorrow.

**Comment by JustinSchieck** [comment]
@MichaelBieniek @lawjeremy Websockets are key

**Comment by MichaelBieniek** [comment]
Closing... outdated.
