### ISSUE TITLE
List of users viewing current board

### ISSUE THREAD

**Issue by lawjeremy** [JustinSchieck/PhoenixRetroBoard#42]
Show a list of users and how many votes they have remaining

**Comment by MichaelBieniek** [comment]
I'll pick this one up.
I'm thinking board creator gets "master" role, all others are "participant". Master can see connected users (their pseudonyms) and remaining votes. Master can also change board options (add/remove columns, change colum titles, permissions)

**Comment by JustinSchieck** [comment]
I think this has been accomplished @MichaelBieniek ? if so lets close off this issue.

**Comment by JustinSchieck** [comment]
@MichaelBieniek Can we close this enhancement

**Comment by MichaelBieniek** [comment]
Sure. Closing.
