### ISSUE TITLE
Add a Timer

### ISSUE THREAD

**Issue by lawjeremy** [JustinSchieck/PhoenixRetroBoard#43]

**Comment by MichaelBieniek** [comment]
We thinking an optional and customizable countdown? At countdown end board updates are locked?

**Comment by lawjeremy** [comment]
Yes exactly.

**Comment by JustinSchieck** [comment]
I'll start this one if your looking at server side stuff Jeremy. Shouldn't you be focusing on not dying going down the mountain tho

**Comment by JustinSchieck** [comment]
I think basic functionality for this has been designed and implimented. unless we want to make alterations, I think we can close this issue.
