### ISSUE TITLE
Update Packages from Security Scans

### ISSUE THREAD

**Issue by JustinSchieck** [JustinSchieck/PhoenixRetroBoard#67]
We have many security issues newly found in a scan.

<img width="929" alt="Screen Shot 2019-09-13 at 8 10 35 AM" src="https://user-images.githubusercontent.com/16888645/64861505-1d360600-d5fe-11e9-966a-2abcf6e36c4f.png">

I will look into updating some of the packages to safe packages.

**Comment by JustinSchieck** [comment]
@MichaelBieniek I belive you mentioned that these were all dependancies of items. Are we sure we cant update the curernt packages to avoid sever issues?

**Comment by MichaelBieniek** [comment]
@JustinSchieck I've updated all the packages I thought needed to be updated + ones from `npm audit`. Will send you a MR.

**Comment by JustinSchieck** [comment]
Thanks. Merged. Closing
